### ISSUE TITLE
Updated wiki pages

### ISSUE THREAD

**Issue by livmari** [DIT112-V20/group-08#105]
### User story
As a person visiting the repository, I want to feel like the repository wiki represents the project contents, so that I can relate back to the wiki when understanding the system features.

### Acceptance criteria
- [x] The wiki has a welcome page with introductory system information.
- [x] The wiki has a page with application installation instructions.
- [ ] The wiki has a hardware set-up instructions page.
- [x] The wiki contains pages for all milestones created during the project.

#### Milestones to update:
- [x] Basic vehicle functions
- [ ] Basic obstacle avoidance
- [x] Gather data from EEG chip
- [x] Car motion with EEG data
- [x] App - back end
- [x] App - front end
- [ ] Connection of hardwares
- [ ] Project documentation
